# numpy.dot()

In [1]:
import numpy as np

### Test 01 - 1D multiplication
In this test two single dimension arrays are multiplied together. <br>
This resultings in  formula: `sum(x0*y0 + x1*y1 +...)`

In [2]:
x = [1,2,3]
y = [1,2,3]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

14


### Test 02 - 2D multiplication

In this test two, two dimensional arrays are multiplied together. <br>
This code fails due to the incompatible shapes of the two inputs.

In [7]:
x = [[1,2,3],[1,2,3]]
y = [[1,2,3],[1,2,3]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray.T)

print(r)
print(yArray.T)

[[14 14]
 [14 14]]
[[1 1]
 [2 2]
 [3 3]]


### Test 03 - 2D multiplication w. compatible shape

In this test two, two dimensional arrays are multiplied together. <br>
The difference between <b>Test 02</b> and <b>Test 03</b> is the shape of array `y` <br>
whihc is transposed so `x` and `y` arrays have compatible shapes.

In [8]:
x = [[1,2,3],[1,2,3]]
y = [[1,1],[2,2],[3,3]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[14 14]
 [14 14]]


### Test 04 - 2D multiplication w. different compatible shape

In this test two, two dimensional arrays are multiplied together. <br>
The difference between <b>Test 03</b> and <b>Test 04</b> is the shape of array `y`.

In [10]:
x = [[1,2,3],[1,2,3]]
y = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[ 6 12 18 24 30]
 [ 6 12 18 24 30]]


### Test 05 - 3D multiplication

In [14]:
x = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]
y = [[[1,2,3],[1,2,3],[1,2,3]]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[[[ 6 12 18]]

  [[ 6 12 18]]

  [[ 6 12 18]]]


 [[[ 6 12 18]]

  [[ 6 12 18]]

  [[ 6 12 18]]]]
