# numpy.dot()

In [2]:
import numpy as np

### Test 01 - 1D multiplication
In this test two single dimension arrays are multiplied together. <br>
This resultings in  formula: `sum(x0*y0 + x1*y1 +...)`

In [3]:
x = [1,2,3]
y = [1,2,3]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

14


### Test 02 - 2D multiplication

In this test two, two dimensional arrays are multiplied together. <br>
This code fails due to the incompatible shapes of the two inputs.

In [4]:
x = [[1,2,3],[1,2,3]]
y = [[1,2,3],[1,2,3]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)
print(yArray.T)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

### Test 03 - 2D multiplication w. compatible shape

In this test two, two dimensional arrays are multiplied together. <br>
The difference between <b>Test 02</b> and <b>Test 03</b> is the shape of array `y` <br>
whihc is transposed so `x` and `y` arrays have compatible shapes.

In [5]:
x = [[1,2,3],[1,2,3]]
y = [[1,1],[2,2],[3,3]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[14 14]
 [14 14]]


### Test 04 - 2D multiplication w. different compatible shape

In this test two, two dimensional arrays are multiplied together. <br>
The difference between <b>Test 03</b> and <b>Test 04</b> is the shape of array `y`.

In [ ]:
x = [[1,2,3],[1,2,3]]
y = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[ 6 12 18 24 30]
 [ 6 12 18 24 30]]


### Test 05 - 2D with single float

In [ ]:
x = 1.2
y = [[[1,2,3.1],[1,2,3.1]]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[[1.2  2.4  3.72]
  [1.2  2.4  3.72]]]


### Test 06 - 3D with single float

In [ ]:
x = 2.1
y = [[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(r)

[[[[2.1 4.2 6.3]
   [2.1 4.2 6.3]]

  [[2.1 4.2 6.3]
   [2.1 4.2 6.3]]

  [[2.1 4.2 6.3]
   [2.1 4.2 6.3]]]]


### Test 07 - 3D with 1D

In [ ]:
x = [[1,2,3],[1,2,3]]
y = [[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)

print(xArray.shape)
print(yArray.shape)
print(r)

ValueError: shapes (2,3) and (1,3,2,3) not aligned: 3 (dim 1) != 2 (dim 2)

### Test 08 - multidimension by 1D multiplication
In this test, a matrix is multiplied by an array.<br>
The shape must match (e.g. 3,4 and 4,)

In [7]:
x = [[[1,2,3],[1,2,3.5],[1,2,4]],[[1.5,2,3],[1.5,2,3.5],[1.5,2,4]]]
y = [1,2,3]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)


print(xArray.shape)
print(yArray.shape)
print(r)
print(r.shape)

(2, 3, 3)
(3,)
[[14.  15.5 17. ]
 [14.5 16.  17.5]]
(2, 3)


In [ ]:
x = [[[1,2,3],[1,2,3.5],[1,2,4]],[[1,2,3],[1,2,3.5],[1,2,4]]]
y = [1,2,3]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)


print(xArray.shape)
print(yArray.shape)
print(r)
print(r.shape)

(2, 4, 3)
(3,)
[[14.  15.5 17.  17. ]
 [14.  15.5 17.  17. ]]
(2, 4)


In [ ]:
x = [[[1,2,3],[1,2,3.5],[1,2,4]],[[1,2,3],[1,2,3.5],[1,2,4]],[[1,2,3],[1,2,3.5],[1,2,4]]]
y = [1,2,3]
xArray = np.array(x)
yArray = np.array(y)
r = np.dot(xArray, yArray)


print(xArray.shape)
print(yArray.shape)
print(r)

(3, 3, 3)
(3,)
[[14.  15.5 17. ]
 [14.  15.5 17. ]
 [14.  15.5 17. ]]
