In [1]:
import numpy as np

In [2]:
x = [[[1,2,3],[1,2,3.5],[1,2,4]],[[1,2,3],[1,2,3.5],[1,2,4]]]

xArray = np.array(x)
print(xArray)

[[[1.  2.  3. ]
  [1.  2.  3.5]
  [1.  2.  4. ]]

 [[1.  2.  3. ]
  [1.  2.  3.5]
  [1.  2.  4. ]]]


In [3]:
xArray + 2

array([[[3. , 4. , 5. ],
        [3. , 4. , 5.5],
        [3. , 4. , 6. ]],

       [[3. , 4. , 5. ],
        [3. , 4. , 5.5],
        [3. , 4. , 6. ]]])

In [5]:
np.add(xArray, xArray)

array([[[2., 4., 6.],
        [2., 4., 7.],
        [2., 4., 8.]],

       [[2., 4., 6.],
        [2., 4., 7.],
        [2., 4., 8.]]])

In [10]:
x = [[1,2,3],[1.5,2.5,3.5]]
y = [2,3,4]
xArray = np.array(x)
yArray = np.array(y)
print(xArray)
print(yArray)

[[1.  2.  3. ]
 [1.5 2.5 3.5]]
[2 3 4]


In [11]:
np.add(xArray, yArray)

array([[3. , 5. , 7. ],
       [3.5, 5.5, 7.5]])